# -*- coding: utf-8 -*-
"""ticket regn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHuiDxJDOYwmEBe0czWRVsmhje1Cazf1
"""

userid = ["ravi", "raja", "ramu"]
password = ["1330", "143", "916"]
username = input("Enter your userid :")

if username==userid[0]:
  password1=input("Enter your password :")
  if password1==password[0]:
    print("Welcome "+ userid[0])
    info = {
        "doj":"10-08-2018",
        "from":"madurai",
        "to":"chennai"
    }
    print(info)
  else:
    print("incorrect password")

elif username==userid[1]:
  password2=input("Enter your password :")
  if password2==password[1]:
    print("Welcome "+ userid[1])
    info = {
        "doj":"03-08-2018",
        "from":"delhi",
        "to":"chennai"
    }
    print(info)
  else:
    print("incorrect password")

elif username==userid[2]:
  password3=input("Enter your password :")
  if password3==password[2]:
    print("Welcome "+ userid[2])
    info = {
        "doj":"04-08-2018",
        "from":"mumbai",
        "to":"chennai"
    }
    print(info)
  else:
    print("incorrect password")
else:
  print("user does not exist!")
